const PDFDocument = require('pdfkit');

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const ML = 50;
const MR = 50;
const CW = PAGE_W - ML - MR;
const FONT = 'Helvetica';
const FB = 'Helvetica-Bold';
const BLUE = '#1e40af';
const DARK = '#1e293b';
const GRAY = '#64748b';
const LG = '#f1f5f9';
const BORDER = '#cbd5e1';
const WHITE = '#ffffff';

function fmtDate(d) {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}
function fmtIST(d) {
  const opts = { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false };
  const parts = new Intl.DateTimeFormat('en-CA', opts).formatToParts(d);
  const m = {}; parts.forEach(p => { m[p.type] = p.value; });
  return `${m.year}-${m.month}-${m.day} ${m.hour}:${m.minute}`;
}

function drawBox(doc, x, y, w, h) {
  doc.rect(x, y, w, h).strokeColor(BLUE).lineWidth(0.5).stroke();
}

function drawHeader(doc, title, classification) {
  drawBox(doc, ML, 30, CW, 110);
  doc.fontSize(10).font(FB).fillColor(DARK);
  doc.text('DEPARTMENT OF FORENSIC MEDICINE', ML, 38, { align: 'center', width: CW });
  doc.fontSize(8).font(FONT).fillColor(GRAY);
  doc.text('MEDICO-LEGAL INFORMATION MANAGEMENT SYSTEM (MLIMS)', ML, 54, { align: 'center', width: CW });
  doc.moveTo(ML + 10, 72).lineTo(ML + CW - 10, 72).strokeColor(BLUE).lineWidth(0.5).stroke();
  doc.fontSize(12).font(FB).fillColor(DARK);
  doc.text(title, ML, 78, { align: 'center', width: CW });

  const metaY = 104;
  doc.fontSize(7).font(FONT).fillColor(GRAY);
  doc.text(`Report Date: ${doc._reportDate || fmtDate(new Date())}`, ML + 8, metaY);
  doc.text(`Generated On: ${doc._generatedOn || fmtIST(new Date())} IST`, ML + 8, metaY + 12);

  doc.font(FONT).fillColor(GRAY);
  doc.text(`Generated By: ${doc._generatedBy || 'System'}`, ML + CW / 2, metaY, { width: CW / 2 - 8, align: 'right' });
  doc.font(FB).fillColor(BLUE);
  doc.text(`Classification: ${classification || 'CONFIDENTIAL'}`, ML + CW / 2, metaY + 12, { width: CW / 2 - 8, align: 'right' });

  return 150;
}

function drawSection(doc, y, title) {
  drawBox(doc, ML, y, CW, 24);
  doc.fontSize(10).font(FB).fillColor(DARK);
  doc.text(title, ML + 8, y + 6);
  doc.font(FONT).fillColor(GRAY);
  return y + 32;
}

function drawKpiRow(doc, startY, cards) {
  const n = cards.length;
  const gap = 6;
  const cardW = (CW - (n - 1) * gap - 16) / n;
  const ch = 44;
  drawBox(doc, ML, startY, CW, ch + 8);
  let x = ML + 8;
  cards.forEach((c, i) => {
    doc.rect(x, startY + 4, cardW, ch).fillAndStroke(LG, BORDER);
    doc.fontSize(7).font(FB).fillColor(DARK);
    doc.text(`${c.label}: ${c.value}`, x + 6, startY + 12, { width: cardW - 12, align: 'center' });
    doc.font(FONT).fillColor(GRAY);
    x += cardW + gap;
    if (i < n - 1) {
      doc.moveTo(x - gap / 2, startY + 6).lineTo(x - gap / 2, startY + 4 + ch).strokeColor(BORDER).lineWidth(0.3).stroke();
    }
  });
  return startY + ch + 16;
}

function drawTable(doc, startY, headers, rows, opts = {}) {
  const fs = opts.fs || 7.5;
  const hr = opts.hr || 18;
  const hbg = BLUE;
  const cw = opts.cw || headers.map(() => (CW - 16) / headers.length);
  const tw = cw.reduce((s, w) => s + w, 0);
  const xo = ML + 8;

  let y = startY;
  let cur = xo;

  doc.rect(xo, y, tw, hr).fill(hbg);
  headers.forEach((h, i) => {
    doc.fontSize(fs).font(FB).fillColor(WHITE);
    doc.text(h, cur + 3, y + 4, { width: cw[i] - 6, align: 'center' });
    cur += cw[i];
  });
  y += hr;

  rows.forEach((row, ri) => {
    if (y + hr > PAGE_H - 70) {
      drawFooter(doc, ri);
      doc.addPage();
      y = drawHeader(doc, doc._reportTitle, doc._classification);
      startY = y;
      cur = xo;
      doc.rect(xo, y, tw, hr).fill(hbg);
      headers.forEach((h, i) => {
        doc.fontSize(fs).font(FB).fillColor(WHITE);
        doc.text(h, cur + 3, y + 4, { width: cw[i] - 6, align: 'center' });
        cur += cw[i];
      });
      y += hr;
    }
    if (ri % 2 === 1) {
      doc.rect(xo, y, tw, hr).fill(LG);
    }
    cur = xo;
    row.forEach((val, i) => {
      doc.fontSize(fs).font(FONT).fillColor(DARK);
      doc.text(val != null ? String(val) : '', cur + 3, y + 4, { width: cw[i] - 6, align: 'center' });
      cur += cw[i];
    });
    y += hr;
  });

  doc.rect(xo, startY, tw, y - startY + 2).strokeColor(BORDER).lineWidth(0.5).stroke();
  return y + 4;
}

function drawSignature(doc, y) {
  y += 24;
  drawBox(doc, ML, y, CW, 36);
  doc.moveTo(ML + 12, y + 16).lineTo(ML + CW / 2 - 12, y + 16).strokeColor(DARK).lineWidth(0.5).stroke();
  doc.fontSize(8).font(FONT).fillColor(GRAY).text('Medical Officer Signature', ML + 12, y + 20);
  doc.moveTo(ML + CW / 2 + 12, y + 16).lineTo(ML + CW - 12, y + 16).strokeColor(DARK).lineWidth(0.5).stroke();
  doc.fontSize(8).font(FONT).fillColor(GRAY).text('Departmental Stamp / Seal', ML + CW / 2 + 12, y + 20, { width: CW / 2 - 24, align: 'right' });
  return y + 40;
}

function drawFooter(doc, pageNum) {
  const y = PAGE_H - 35;
  doc.moveTo(ML, y).lineTo(ML + CW, y).strokeColor(BORDER).lineWidth(0.5).stroke();
  doc.fontSize(7).font(FONT).fillColor(GRAY);
  doc.text(`Page ${pageNum || 1} of ${doc._totalPages || 1}`, ML, y + 5);
  doc.text('MLIMS Official Document', ML + CW, y + 5, { align: 'right' });
}

function initDoc(doc, title, cls, genBy, reportDate) {
  doc._reportTitle = title;
  doc._classification = cls || 'CONFIDENTIAL';
  doc._generatedBy = genBy || 'System';
  doc._generatedOn = fmtIST(new Date());
  doc._reportDate = reportDate || fmtDate(new Date());
  doc._totalPages = 0;
  doc._pageCount = 0;
  doc.on('pageAdded', () => { doc._pageCount++; });
  doc.on('end', () => { doc._totalPages = doc._pageCount + 1; });
  doc.font(FONT).fontSize(10);
}

// ── Daily Report ─────────────────────────────────────────────────────────────
function generateDailyReport(res, data, genBy) {
  const doc = new PDFDocument({ size: 'A4', margin: 0 });
  initDoc(doc, 'OFFICIAL DAILY CASE REPORT', 'CONFIDENTIAL', genBy, data.reportDate);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="daily-report-${data.reportDate}.pdf"`);
  doc.pipe(res);

  let y = drawHeader(doc, 'OFFICIAL DAILY CASE REPORT', 'CONFIDENTIAL');
  y = drawSection(doc, y, 'SUMMARY METRICS');
  y = drawKpiRow(doc, y, [
    { label: 'Total Cases', value: data.summary.total_cases || 0 },
    { label: 'Clinical (MLEF)', value: data.summary.clinical_count || 0 },
    { label: 'Autopsies', value: data.summary.autopsy_count || 0 },
    { label: 'Pending', value: data.pendingLabs || 0 },
  ]);
  y = drawSection(doc, y, 'DAILY CASE DETAILS');
  const hdrs = ['TIME', 'CASE REF NO', 'PATIENT NAME', 'CATEGORY', 'POLICE STATION'];
  const cws = [55, 120, 110, 70, 140];
  const rows = data.details.map(r => [
    (r.exam_time || r.time_of_pm || '').slice(0, 5) || '--:--',
    r.case_number || '',
    r.patient_name || '',
    r.case_type === 'clinical' ? 'Clinical' : r.case_type === 'postmortem' ? 'Postmortem' : (r.case_type || ''),
    r.station_name || '',
  ]);
  y = drawTable(doc, y, hdrs, rows, { cw: cws, hr: 17 });
  y = drawSignature(doc, y);
  drawFooter(doc, 1);
  doc.end();
}

// ── Monthly Report ───────────────────────────────────────────────────────────
function generateMonthlyReport(res, data, genBy) {
  const doc = new PDFDocument({ size: 'A4', margin: 0 });
  const mn = new Date(data.year, data.month - 1).toLocaleString('en-US', { month: 'long' });
  initDoc(doc, `MONTHLY REPORT — ${mn} ${data.year}`, 'CONFIDENTIAL', genBy);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="monthly-report-${data.year}-${String(data.month).padStart(2, '0')}.pdf"`);
  doc.pipe(res);

  let y = drawHeader(doc, `MONTHLY REPORT — ${mn} ${data.year}`, 'CONFIDENTIAL');
  y = drawSection(doc, y, 'PERFORMANCE SUMMARY');
  y = drawKpiRow(doc, y, [
    { label: 'Total Admissions', value: data.kpis.total_admissions || 0 },
    { label: 'Clinical Cases', value: data.kpis.clinical_count || 0 },
    { label: 'Autopsies Conducted', value: data.kpis.autopsies_conducted || 0 },
    { label: 'MLR Issued', value: data.kpis.mlr_issued || 0 },
  ]);
  y = drawSection(doc, y, 'CATEGORY BREAKDOWN');
  if (data.breakdown && data.breakdown.length > 0) {
    const hdrs = ['CATEGORY', 'CLINICAL COUNT', 'AUTOPSY COUNT', 'TOTAL VOLUME'];
    const cws = [140, 115, 115, 115];
    const rows = data.breakdown.map(r => [
      r.category || '', String(r.clinical_count || 0), String(r.autopsy_count || 0), String(r.total_volume || 0),
    ]);
    y = drawTable(doc, y, hdrs, rows, { cw: cws });
  } else {
    doc.fontSize(9).font(FONT).fillColor(GRAY).text('No breakdown data available.', ML + 8, y + 6);
    y += 24;
  }
  y = drawSignature(doc, y);
  drawFooter(doc, 1);
  doc.end();
}

// ── Pending Report ───────────────────────────────────────────────────────────
function generatePendingReport(res, data, genBy) {
  const doc = new PDFDocument({ size: 'A4', margin: 0 });
  initDoc(doc, 'PENDING CASES BOTTLENECK TRACKER', 'CONFIDENTIAL', genBy);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="pending-bottleneck-report.pdf"`);
  doc.pipe(res);

  let high = 0, med = 0;
  (data.cases || []).forEach(c => { if (c.risk_level === 'high') high++; else if (c.risk_level === 'medium') med++; });

  let y = drawHeader(doc, 'PENDING CASES BOTTLENECK TRACKER', 'CONFIDENTIAL');
  y = drawSection(doc, y, 'BOTTLENECK SUMMARY');
  y = drawKpiRow(doc, y, [
    { label: 'Total Pending', value: data.total || 0 },
    { label: 'Threshold (Days)', value: data.threshold || 7 },
    { label: 'High Risk', value: high },
    { label: 'Medium Risk', value: med },
  ]);
  y = drawSection(doc, y, 'PENDING CASES DETAILS');
  const hdrs = ['CASE NO', 'PATIENT', 'DAYS', 'RISK', 'BOTTLENECK', 'DOCTOR'];
  const cws = [100, 95, 45, 50, 110, 100];
  const rows = (data.cases || []).map(r => [
    r.case_number || '', r.patient_name || '', String(r.days_pending || 0),
    (r.risk_level || '').toUpperCase(), (r.bottleneck_reason || '').replace(/_/g, ' '), r.doctor_name || '',
  ]);
  y = drawTable(doc, y, hdrs, rows, { cw: cws });
  y = drawSignature(doc, y);
  drawFooter(doc, 1);
  doc.end();
}

// ── Court Report ─────────────────────────────────────────────────────────────
function generateCourtReport(res, data, genBy) {
  const doc = new PDFDocument({ size: 'A4', margin: 0 });
  initDoc(doc, 'COURT SUMMONS & TRIAL REGISTER', 'CONFIDENTIAL', genBy);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="court-trial-register.pdf"`);
  doc.pipe(res);

  let y = drawHeader(doc, 'COURT SUMMONS & TRIAL REGISTER', 'CONFIDENTIAL');
  y = drawSection(doc, y, 'TRIAL SCHEDULE');
  y = drawKpiRow(doc, y, [
    { label: 'Total Trials', value: (data.trials || []).length },
    { label: 'MLR Dispatched', value: (data.trials || []).filter(t => t.mlr_status === 'dispatched').length },
    { label: 'Receipt Verified', value: (data.trials || []).filter(t => t.receipt_status === 'verified').length },
    { label: 'Upcoming (30d)', value: (data.trials || []).filter(t => t.trial_date).length },
  ]);
  y = drawSection(doc, y, 'TRIAL DETAILS');
  const hdrs = ['TRIAL DATE', 'COURT CASE NO', 'COURT NAME', 'MLR STATUS', 'RECEIPT'];
  const cws = [80, 100, 130, 90, 100];
  const rows = (data.trials || []).map(r => [
    r.trial_date ? new Date(r.trial_date).toLocaleDateString('en-GB') : '',
    r.court_case_no || '', r.court_name || '',
    (r.mlr_status || '').toUpperCase(), (r.receipt_status || '').toUpperCase(),
  ]);
  y = drawTable(doc, y, hdrs, rows, { cw: cws });
  y = drawSignature(doc, y);
  drawFooter(doc, 1);
  doc.end();
}

// ── Statistical Report ───────────────────────────────────────────────────────
function generateStatisticalReport(res, data, genBy) {
  const doc = new PDFDocument({ size: 'A4', margin: 0 });
  initDoc(doc, `ADVANCED ANALYTICS & STATISTICAL REPORT — ${data.year}`, 'CONFIDENTIAL', genBy);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="statistical-report-${data.year}.pdf"`);
  doc.pipe(res);

  let y = drawHeader(doc, `ADVANCED ANALYTICS & STATISTICAL REPORT — ${data.year}`, 'CONFIDENTIAL');
  y = drawSection(doc, y, 'YEARLY OVERVIEW');
  y = drawKpiRow(doc, y, [
    { label: 'Total Cases', value: data.totalCases || 0 },
    { label: 'Months Active', value: (data.monthlyTrend || []).length },
    { label: 'COD Groups', value: (data.causeOfDeath || []).length },
    { label: 'Age Groups', value: (data.demographics || []).length },
  ]);

  y = drawSection(doc, y, 'MONTHLY TREND');
  if (data.monthlyTrend && data.monthlyTrend.length > 0) {
    const hdrs = ['MONTH', 'CLINICAL', 'POSTMORTEM', 'TOTAL'];
    const cws = [120, 120, 120, 120];
    const rows = data.monthlyTrend.map(r => [
      r.month_label || '', String(r.clinical_count || 0), String(r.pm_count || 0), String(r.total || 0),
    ]);
    y = drawTable(doc, y, hdrs, rows, { cw: cws, hr: 16 });
    y += 4;
  }

  y = drawSection(doc, y, 'CAUSE OF DEATH DISTRIBUTION');
  if (data.causeOfDeath && data.causeOfDeath.length > 0) {
    const hdrs = ['CAUSE GROUP', 'COUNT', 'PERCENTAGE'];
    const cws = [240, 120, 120];
    const rows = data.causeOfDeath.map(r => [r.cause_group || '', String(r.count || 0), `${r.pct || '0'}%`]);
    y = drawTable(doc, y, hdrs, rows, { cw: cws, hr: 16 });
    y += 4;
  }

  y = drawSection(doc, y, 'DEMOGRAPHIC BREAKDOWN');
  if (data.demographics && data.demographics.length > 0) {
    const hdrs = ['AGE GROUP', 'MALE', 'FEMALE', 'TOTAL', '% SHARE'];
    const cws = [100, 100, 100, 90, 90];
    const rows = data.demographics.map(r => [
      r.age_group || '', String(r.male_cases || 0), String(r.female_cases || 0),
      String(r.total_volume || 0), `${r.pct || '0'}%`,
    ]);
    y = drawTable(doc, y, hdrs, rows, { cw: cws, hr: 16 });
  }

  y = drawSignature(doc, y);
  drawFooter(doc, 1);
  doc.end();
}

function generateCombinedReport(res, data, genBy) {
  const doc = new PDFDocument({ size: 'A4', margin: 0 });
  initDoc(doc, 'ADMISSION TRENDS & CAUSE OF DEATH & DEMOGRAPHIC HEATMAP', 'CONFIDENTIAL', genBy);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=\"combined-report.pdf\"`);
  doc.pipe(res);

  let y = drawHeader(doc, 'ADMISSION TRENDS & CAUSE OF DEATH & DEMOGRAPHIC HEATMAP', 'CONFIDENTIAL');
  // Admission Trends (use KPI from statistical data)
  y = drawSection(doc, y, 'ADMISSION TRENDS');
  if (data.kpis) {
    y = drawKpiRow(doc, y, [
      { label: 'Total Admissions', value: data.kpis.total_admissions || 0 },
      { label: 'Clinical Cases', value: data.kpis.clinical_count || 0 },
      { label: 'Autopsies Conducted', value: data.kpis.autopsy_count || 0 },
      { label: 'MLR Issued', value: data.kpis.mlr_issued || 0 },
    ]);
  }

  // Cause of Death Distribution
  if (data.causeOfDeath && data.causeOfDeath.length > 0) {
    y = drawSection(doc, y, 'CAUSE OF DEATH DISTRIBUTION');
    const hdrs = ['CAUSE GROUP', 'COUNT', 'PERCENTAGE'];
    const cws = [240, 120, 120];
    const rows = data.causeOfDeath.map(r => [r.cause_group || '', String(r.count || 0), `${r.pct || '0'}%`]);
    y = drawTable(doc, y, hdrs, rows, { cw: cws, hr: 16 });
  }

  // Demographic Heatmap
  if (data.demographics && data.demographics.length > 0) {
    y = drawSection(doc, y, 'DEMOGRAPHIC HEATMAP');
    const hdrs = ['AGE GROUP', 'MALE', 'FEMALE', 'TOTAL', '% SHARE'];
    const cws = [100, 100, 100, 90, 90];
    const rows = data.demographics.map(r => [
      r.age_group || '', String(r.male_cases || 0), String(r.female_cases || 0),
      String(r.total_volume || 0), `${r.pct || '0'}%`
    ]);
    y = drawTable(doc, y, hdrs, rows, { cw: cws, hr: 16 });
  }

  y = drawSignature(doc, y);
  drawFooter(doc, 1);
  doc.end();
}


module.exports = {
  generateDailyReport, generateMonthlyReport, generatePendingReport,
  generateCourtReport, generateStatisticalReport,
};
