import React, { useEffect, useState, useCallback, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import { Download, Printer, Calendar, Filter } from 'lucide-react';

const statusBadge = (status) => {
  const map = {
    registered: 'bg-slate-100 text-slate-700',
    under_investigation: 'bg-amber-100 text-amber-700',
    pending_report: 'bg-orange-100 text-orange-700',
    completed: 'bg-green-100 text-green-700',
    closed: 'bg-indigo-100 text-indigo-700',
  };
  return map[status] || 'bg-slate-100 text-slate-700';
};

const ReportDailyPage = () => {
  const { user } = useAuth();
  const isAdmin = user?.role === 'admin';
  const [reportDate, setReportDate] = useState(new Date().toISOString().slice(0, 10));
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const reportRef = useRef(null);

  const fetchReport = useCallback(() => {
    setLoading(true);
    api.get(`/reporting/daily?date=${reportDate}`)
      .then(res => setData(res.data))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [reportDate]);

  useEffect(() => { fetchReport(); }, [fetchReport]);

  const handlePrint = () => window.print();
  const handleExportPdf = async () => {
    try {
      const response = await api.get(`/reporting/daily/pdf?date=${reportDate}`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(response.data);
      const a = document.createElement('a'); a.href = url; a.download = `daily-report-${reportDate}.pdf`; a.click();
      window.URL.revokeObjectURL(url);
    } catch (err) { console.error(err); }
  };

  return (
    <div ref={reportRef} className="max-w-6xl mx-auto space-y-6">
        <div className="print-header text-center mb-6">
          <h1 className="text-2xl font-bold">DEPARTMENT OF FORENSIC MEDICINE</h1>
          <h2 className="text-xl">MEDICO-LEGAL INFORMATION MANAGEMENT SYSTEM (MLIMS)</h2>
          <h3 className="text-lg font-semibold">OFFICIAL DAILY CASE REPORT</h3>
          <p className="text-sm">
            Report Date: {new Date(reportDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} &nbsp;|&nbsp;
            Generated By: Admin (ID: {user?.id || '9'})
          </p>
          <p className="text-sm">Generated On: {new Date().toLocaleString('en-GB', { hour12: false })} IST</p>
          <p className="text-sm font-bold uppercase text-red-600">Classification: CONFIDENTIAL</p>
        </div>
      <div className="flex items-center justify-between no-print">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Daily Case Report</h2>
          <p className="text-slate-500 text-sm mt-1">Operational summary of clinical examinations and autopsy admissions</p>
        </div>
        {isAdmin && <div className="flex gap-2">
          <button onClick={handleExportPdf} className="inline-flex items-center px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-200 rounded-lg hover:bg-slate-50"><Download className="w-4 h-4 mr-2" />Export PDF</button>
          <button onClick={handlePrint} className="inline-flex items-center px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-200 rounded-lg hover:bg-slate-50"><Printer className="w-4 h-4 mr-2" />Print</button>
        </div>}
      </div>

      <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200 flex items-center gap-4 flex-wrap no-print">
        <div className="flex items-center gap-2">
          <Calendar className="w-4 h-4 text-slate-400" />
          <input type="date" value={reportDate} onChange={e => setReportDate(e.target.value)}
            className="border border-slate-200 rounded-lg px-3 py-2 text-sm" />
        </div>
        <button onClick={fetchReport} disabled={loading}
          className="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-primary-600 rounded-lg hover:bg-primary-700">
          <Filter className="w-4 h-4 mr-2" />Apply
        </button>
      </div>

      {loading && <div className="text-center py-12 text-slate-400">Loading report...</div>}

      {data && (
        <>
          <div className="grid grid-cols-4 gap-4">
            {[
              { label: 'Total Cases', value: data.summary.total_cases, color: 'text-slate-900' },
              { label: 'Clinical (MLEF)', value: data.summary.clinical_count, color: 'text-blue-600' },
              { label: 'Autopsies', value: data.summary.autopsy_count, color: 'text-slate-700' },
              { label: 'Pending Lab Tests', value: data.pendingLabs, color: 'text-amber-600' },
            ].map((k, i) => (
              <div key={i} className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
                <p className="text-sm text-slate-500 mb-1">{k.label}</p>
                <p className={`text-3xl font-bold ${k.color}`}>{k.value}</p>
              </div>
            ))}
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="bg-slate-50 px-6 py-4 border-b border-slate-200">
              <h3 className="font-semibold text-slate-800">Daily Case Details &mdash; {data.reportDate}</h3>
            </div>
            {data.details.length === 0 ? (
              <div className="p-8 text-center text-slate-400">No cases registered on this date.</div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-sm">
                  <thead className="bg-slate-50 text-slate-600 font-semibold border-b border-slate-200">
                    <tr>
                      <th className="px-6 py-4">Time</th>
                      <th className="px-6 py-4">Case Ref No</th>
                      <th className="px-6 py-4">Patient / Deceased</th>
                      <th className="px-6 py-4">Category</th>
                      <th className="px-6 py-4">Police Station</th>
                      <th className="px-6 py-4">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {data.details.map((row, i) => (
                      <tr key={row.case_id || i} className="hover:bg-slate-50 transition-colors">
                        <td className="px-6 py-4 text-slate-600">{row.exam_time || row.time_of_pm || '--'}</td>
                        <td className="px-6 py-4 font-medium text-slate-900">{row.case_number}</td>
                        <td className="px-6 py-4">{row.patient_name}</td>
                        <td className="px-6 py-4 capitalize">{row.death_category || row.case_type}</td>
                        <td className="px-6 py-4">{row.station_name}</td>
                        <td className="px-6 py-4">
                          <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-bold ${statusBadge(row.status)}`}>
                            {row.status.replace(/_/g, ' ')}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
};

export default ReportDailyPage;
